version: '3.8'

services:

  app:
    build: .
    container_name: portfolio-app

    ports:
      - "8000:80"

    volumes:
      - .:/var/www/html

    depends_on:
      - database

  database:
    image: mysql:8.0
    container_name: portfolio-db

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: portfoliodb

    ports:
      - "3307:3306"

    volumes:
      - db_data:/var/lib/mysql
      - ./tables:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: portfolio-pma

    restart: always

    ports:
      - "8081:80"

    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: root

    depends_on:
      - database

volumes:
  db_data: